apiVersion: v1
kind: Pod
metadata:
  name: demo-configmap
spec:
  containers:
    - name: demo-configmap
      image: ghcr.io/vvision/demo-k8s:main
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
      envFrom:
        - configMapRef:
            name: demo-configmap
